name: myapp
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  pdf: ^3.11.3
  printing: ^5.14.2
  provider: ^6.1.2
  intl: ^0.18.1  # ✅ Versión compatible con Flutter estable
  sqflite: ^2.4.2
  mysql1: ^0.20.0
  path_provider: ^2.1.5
  shared_preferences: ^2.2.2  # ✅ Para almacenamiento de preferencias locales

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  test: ^1.24.0
  
flutter:
  uses-material-design: true
